### ISSUE TITLE
Update FILE_UPLOAD_MAX_MEMORY_SIZE

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/app-backend#178]
Django's default is to limit file uploads to 2.5MB. The UI is currently set to 15MB which feels like a decent line in the sand. Thoughts on what the default should be across our services?

@jgwerner @johngriebel @jkp85

**Comment by johngriebel** [comment]
I'm fine with 15 MB, it doesnt really matter all that much to me as long as it's agreed upon

**Comment by jgwerner** [comment]
@johngriebel @raygesualdo how should the value be set? 

For example:

    1024 X 15 = 15360

**Comment by johngriebel** [comment]
@jgwerner sure, that would be fine.

@raygesualdo Looking at the Django documentation, it appears 2.5MB is the limit after which Django will stream the file to `/tmp/`. As far as I can tell, there is no built-in limitation file upload size in Django. However, Django _does_ limit request body data to 2.5MB by default, which would restrict uploads using the `base64_data` field. Can you confirm that you see a `SuspiciousOperation`?

Perhaps these implementation details aren't all that relevant, but it does raise the question; should we increase the file size that Django will load into memory? It might be wise to do so because this is what would happen when a user uploads 25MB of base64 data: 
1.) The client uploads data to our server.
2.) Django then uses that data to create the file but must stream it to the disk.
3.) Once step 2 is complete, Django then moves the file from `/tmp` to the final location.

In this way, we've essentially uploaded the file twice. Increasing the maximum size of files loaded into memory could eliminate step 2 and would (almost) cut upload times in half for any file larger than 2.5MB. Raising this limitation would make regular form data file uploads faster as well, but the difference wouldn't be quite as large. The drawback to doing so, of course, is consuming more memory on the server. I'm not sure if 25MB is a large chunk of RAM to eat up for this purpose, or not. That's a question for @jgwerner and probably @roachmd.

**Comment by johngriebel** [comment]
@jgwerner @raygesualdo Should this be an env var, or just hardcoded into our settings?
