### ISSUE TITLE
Cannot delete username through api

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#189]
A person can delete their user-id through the API, but the username they used is not deleted.

Using Runscope.
Endpoint: https://dev-api.3blades.ai/users/profiles/{{user_id}}/
Method: DELETE

To view output of Runscope: https://www.runscope.com/radar/vzxz7svfdhxu/f19644a0-548c-45f1-9529-b55c5a71b5dd/history/80bd89cb-2536-4bc0-91c9-b4c06b1351c5

Related to #198

**Comment by johngriebel** [comment]
@pthakkar230 - Are you sure deletion is the issue? Looking at the Runscope output, it appears that delete worked as expected; `HTTP 204: No Content` is the correct response.  I do see a failure for `POST` though. It's complaining that a user with the username "runscopeTesterUser" already exists, which is true - it appears that there are two entries for the user creation test.

**Comment by johngriebel** [comment]
After review, this is a valid issue after all. What's happening is upon user "deletion," the User's database entry is only marked as inactive, instead of truly being deleted. Soft deletion is the correct action, but we use Django's built-in AuthUser model, which has a uniqueness constraint on `username`. We need to come up with a way to override that uniqueness constraint.
