### ISSUE TITLE
Testing Project Files via Runscope

### ISSUE THREAD

**Issue by pthakkar230** [3Blades/app-backend#213]
To test the `project_files` endpoint via Runscope, we need to be able to upload a file. Right now, Runscope doesn't have that functionality.

Specified in docs here: https://docs.3blades.io/v1.1/reference#projects_project_files_create-1
We are using the dev-api.3blades.ai environment.

Does anyone have any input on how to automate testing for this feature? Otherwise, we might have to just do manual tests.

**Comment by johngriebel** [comment]
@pthakkar230, for now, we could test the upload using the `base64_data` field. This won't test `multipart/form-data` uploads, but it does provide some testing of the upload endpoints. DM me on Slack, and I can help you get a test working.

**Comment by pthakkar230** [comment]
Tried using `base64_data` field, but for some reason, Runscope cannot set the `id` of the project file when it is uploaded. I am getting a success code 201, so I am not sure what is going wrong.

https://www.runscope.com/radar/vzxz7svfdhxu/891bcee9-ca15-4f2d-84f0-80fbabef4195/history/7aaf8467-b810-4881-91b5-59aee4eaadd5

**Comment by johngriebel** [comment]
@pthakkar230 It looks like your test is just a bit misconfigured. See this error: `  Failed to set 'project_file_id' — Non-numeric index on a list element 'id' in JSON.`, then note that the response is actually a _list_ of the created project files since multiple files can be created at once. It seems like you need to do something like `response[0]['id']`, though I'm not sure exactly how to construct that in runscope.

**Comment by pthakkar230** [comment]
Tested, it is working. Closing issue.
