### ISSUE TITLE
Test All Possible Actions for Triggers

### ISSUE THREAD

**Issue by johngriebel** [3Blades/app-backend#262]
After some discussion with @jkp85, it has been decided that [devops/18](https://github.com/3Blades/devops/issues/18) is best handled as a Django unit test, using `LiveServerTestCase`.

**Comment by johngriebel** [comment]
This is related to #246.

**Comment by jkp85** [comment]
@jgwerner @johngriebel Action is in short anything that user or our system performs (user request, server response, async action). So we are actually testing all actions in Runscope. It's not like any action can be matched with all http methods. There is no action `project-list` `DELETE` because it makes no sense. You can't delete all projects in one go. There are specific combinations that will work, all of them are documented in swagger and all of them are tested in runscope.

**Comment by jgwerner** [comment]
@johngriebel I talked to @johngriebel about this and showed him an example message. You can test in our [interactive API docs](https://docs.3blades.io/v1.2/reference#triggers_create), but basically, regardless of the method selected some of the actions are not recognized as valid actions. For example, select `project-list` as cause and `serger-list` as effect (both with GET methods), the response is:

```
{
  "effect": {
    "non_field_errors": [
      "There is no action with name server-list"
    ]
  }
}
```

**Comment by jkp85** [comment]
@jgwerner This is validation error of 'server-list' action. I'll fix it.

**Comment by jkp85** [comment]
@jgwerner Above error is due to our nested api structure. In order for this to work I need to know for which project this action will be. Our nested api structure requires to specify every path parameter for an url ex. `/<version>/<namespace>/projects/<project_id>/servers/` in order to build this url I need version, namespace and project_id. I can take version and namespace from triggers endpoint url, but project_id needs to be specified. In other words I need a context for trigger. `project-list` doesn't require any context, but `server-list` does.

**Comment by jkp85** [comment]
@raygesualdo  How do you think we will create triggers in UI? Project level, server level? In cli tools user can add current project to config file.

**Comment by johngriebel** [comment]
Closing this as we decided to go live without triggers in 1.0, and redesign them for 1.x. See #276
