### ISSUE TITLE
API testing errors

### ISSUE THREAD

**Issue by jgwerner** [3Blades/app-backend#338]
API errors:

/users endpoints:

- States that system only accepts POST: error with GET /v1/users/user_id/avatar/
- https://dev-api.3blades.ai/v1/users/user_id/api-key/reset/ 404 with both GET/POST
- [Boundary](https://stackoverflow.com/questions/2198470/javascript-uploading-a-file-without-a-file/2198524#2198524) in multi part uploads, for avatar endpoints. Probably just a config issue.
- POST /v1/users/{{user_id}}/ssh-key/reset/ returning a 200, not 201. Normal?

/billing endpoints:

- For /v1/admin/billing/cards/, RelatedObjectDoesNotExist has no customer error (500).
- API docs correctly return new card record with POST /v1/{{namespace}}/billing/cards/. Test returns a 500 error.
- Can’t delete a project, insufficient permissions

/projects endpoints

- getting a trigger with GET /v1/namespace/projects/project_id/servers/server_id/triggers/id/ doesn’t work. Successfully created a trigger but could not retrieve the trigger using this endpoint. Validated project, server id and trigger id. Test failed in API docs too.

There's more, will add as I run throught all tests.

/cc @johngriebel

**Comment by johngriebel** [comment]
/users endpoints:

- States that system only accepts POST: error with GET /v1/users/user_id/avatar/

This is the correct behavior. In order to `GET` an avatar, one should send a `GET` request to the `/users/profiles` endpoint. The `POST` is its own endpoint to avoid complicating the rest of the profiles endpoint for a single field.
- https://dev-api.3blades.ai/v1/users/user_id/api-key/reset/ 404 with both GET/POST

Remove `reset/` from the URL. We don't really have the concept of resetting the API key, we just generate a new one if you send a request to this endpoint. Further, the endpoint only accepts `GET` requests since you'll never send information (other than Authorization headers to it).

- [Boundary](https://stackoverflow.com/questions/2198470/javascript-uploading-a-file-without-a-file/2198524#2198524) in multi part uploads, for avatar endpoints. Probably just a config issue.


- POST /v1/users/{{user_id}}/ssh-key/reset/ returning a 200, not 201. Normal?

It's normal in that we choose to return `200 OK` on success here instead of `201 CREATED`. I think that's the correct thing to do here since it's a "reset" as opposed to a "create", but I don't have a strong opinion one way or the other.

/billing endpoints:

- For /v1/admin/billing/cards/, RelatedObjectDoesNotExist has no customer error (500).

This is because the user has not yet logged in, so a Customer record hasn't been created for that User yet. I've never been a fan of this behavior, so I'll change it so that the customer record is created at the same time that the user is saved in the database.

- API docs correctly return new card record with POST /v1/{{namespace}}/billing/cards/. Test returns a 500 error.

I would have to see the request you sent to the server or at least the stack trace for the error.

- Can’t delete a project, insufficient permissions

Are you sure this is a problem with billing? This error message is only seen when attempting to delete a project that "you" (the user sending the request) are not the owner of. In other words. the following query should return a record: 
`Collaborator.objects.filter(project=instance, user=user,  owner=True)`

/projects endpoints

- getting a trigger with GET /v1/namespace/projects/project_id/servers/server_id/triggers/id/ doesn’t work. Successfully created a trigger but could not retrieve the trigger using this endpoint. Validated project, server id and trigger id. Test failed in API docs too.

Will look into this one. May have to ping you for more info.

**Comment by johngriebel** [comment]
Closing as done.
